### PR TITLE
[devex] Add Project coding styles (#294)

### PR DESCRIPTION
**Pull request by guillaumejparis**

### CODE REVIEW

**Comment by guillaumejparis** [comment]
@RomuDeuxfois Can you add rules for the Java part ? (we don't have any in OpenCTI)

**Comment by guillaumejparis** [comment]
As we already discussed, in this PR we will only add the Project.xml to mimic opencti

**Comment by guillaumejparis** [comment]
@RomuDeuxfois do we merge this one ?

**Review by RomuDeuxfois — APPROVED** [review]

**Comment by RomuDeuxfois** [comment]
Yes !

**Pull request merged**
