### PR TITLE
[front] prevent adding new document when no admin in inject add docum…

### PR DESCRIPTION
**Pull request by guillaumejparis**
#258

### CODE REVIEW

**Comment by RomuDeuxfois** [comment]
Not directly related to this PR but it might be good to cover it here

When you create a document without a file, the error messages is missing


image

**Comment by RomuDeuxfois** [comment]
I have a weird behavior when I am connected with a no admin user
[screen-capture (13).webm](https://github.com/OpenEx-Platform/openex/assets/53513584/83862ba1-a62f-409a-9e12-14d2843c1f9d)

**Comment by guillaumejparis** [comment]
> I have a weird behavior when I am connected with a no admin user [screen-capture (13).webm](https://github.com/OpenEx-Platform/openex/assets/53513584/83862ba1-a62f-409a-9e12-14d2843c1f9d)

Please retry as i can not reproduce this

**Comment by RomuDeuxfois** [comment]
> > I have a weird behavior when I am connected with a no admin user [screen-capture (13).webm](https://github.com/OpenEx-Platform/openex/assets/53513584/83862ba1-a62f-409a-9e12-14d2843c1f9d)
> 
> Please retry as i can not reproduce this

I can't reproduce, so it's ok

**Review by RomuDeuxfois — APPROVED** [review]

**Pull request merged**
